--apaga todos os dados existentes nas tabelas
BEGIN transaction;

DELETE FROM INTER_PERIODICA;
DELETE FROM INTER_EQUIPA;
DELETE FROM VCOMERCIAL;
DELETE FROM INTERVENCAO;
DELETE FROM TEL_PESSOA;
DELETE FROM COMP_PESSOA;
DELETE FROM ACTIVO;
DELETE FROM TEL_EMPRESA;
ALTER TABLE EQUIPA DROP constraint if EXISTS resp_pessoa;
DELETE FROM PESSOA;
DELETE FROM EQUIPA;
ALTER table if EXISTS EQUIPA
ADD constraint resp_pessoa foreign KEY (responsavel) references PESSOA(id) DEFERRABLE INITIALLY DEFERRED;
DELETE FROM EMPRESA;
DELETE FROM COMPETENCIA;
DELETE FROM ACTIVOTIPO;

COMMIT transaction;


