--apaga todos os dados existentes nas tabelas
DELETE FROM INTER_PERIODICA;
DELETE FROM INTER_EQUIPA;
DELETE FROM VCOMERCIAL;
DELETE FROM INTERVENCAO ;
DELETE FROM TEL_PESSOA;
DELETE FROM COMP_PESSOA;
DELETE FROM ACTIVO;
DELETE FROM TEL_EMPRESA;
DELETE FROM PESSOA;
DELETE FROM EQUIPA;
DELETE FROM EMPRESA;
DELETE FROM COMPETENCIA;
DELETE FROM ACTIVOTIPO;



