--remove modelo fisico
DROP TABLE IF EXISTS INTER_PERIODICA;
DROP TABLE IF EXISTS INTER_EQUIPA;
DROP TABLE IF EXISTS VCOMERCIAL;
DROP TABLE IF EXISTS INTERVENCAO;
DROP TABLE IF EXISTS TEL_PESSOA;
DROP TABLE IF EXISTS COMP_PESSOA;
DROP TABLE IF EXISTS ACTIVO;
DROP TABLE IF EXISTS TEL_EMPRESA;
ALTER table if EXISTS EQUIPA DROP constraint if EXISTS resp_pessoa;
DROP TABLE IF EXISTS PESSOA;
DROP TABLE IF EXISTS EQUIPA;
DROP TABLE IF EXISTS EMPRESA;
DROP TABLE IF EXISTS COMPETENCIA;
DROP TABLE IF EXISTS ACTIVOTIPO;



